### ISSUE TITLE
you should't push useless comments in your code.

### ISSUE THREAD

**Issue by Hussein-shahatet97** [GSG-K3/Ocean-Movies#17]
// let posterimg = document.createElement("img"); // img
        // posterimg.src = `http://image.tmdb.org/t/p/w185${response.results[i].poster_path}`;

        // let moviename = document.createElement("h1");
        // moviename.innerText = response.results[i].title;
        // let movierate = document.createElement("h2");
        // movierate.innerText = response.results[i].vote_average;
        // let movieabout = document.createElement("p");

        // seconddiv.appendChild(posterimg);
        // firstdiv.appendChild(seconddiv);
        // firstdiv.appendChild(moviename);
        // firstdiv.appendChild(movierate);
        // firstdiv.appendChild(infoButton);
        // movielist.appendChild(firstdiv);

**Comment by bayan-404** [comment]
nothing is useless :wink:
